### ISSUE TITLE
Watchlistarr keeps re-adding ignored items, unignoring them

### ISSUE THREAD

**Issue by ALERTua** [nylonee/watchlistarr#10]
- The item gets into the Plex Watchlist
- Before Watchlistarr existed, I had to add such items manually in Radarr/Sonarr, or they were auto-added from IMDB Watchlist.
- After such an item is imported, downloaded, watched, eventually deleted, and ignored, such an item doesn't get imported by IMDB Watchlist again.
- But Watchlistarr auto-adds these items again and unignores them.

**Comment by nylonee** [comment]
Hey, thanks for trying out watchlistarr, I just published it yesterday and it's nice to see people are already trying it out!

Hmm, so watchlistarr is adding the item again because it's on your Plex watchlist, ignoring the fact that it's already been deleted on Sonarr/Radarr, right?

I wonder if there's a way to detect items that have been previously deleted, I'll have a browse through the Sonarr/Radarr APIs

**Comment by nylonee** [comment]
Ah yes, if the movie/tv show is on the Import List Exclusion (Sonarr UI -> Settings -> Import Lists), there's an API for that and I can exclude those movies/tv shows from being re-added

Will that fix your issue? I will probably feature-flag it so that others can decide to override it manually

**Comment by ALERTua** [comment]
> Hmm, so watchlistarr is adding the item again because it's on your Plex watchlist, ignoring the fact that it's already been deleted on Sonarr/Radarr, right?

Ignoring the fact that the item is already ignored
![image](https://github.com/nylonee/watchlistarr/assets/8375129/91c1df8c-872a-4977-b5f2-f57949625620)

> Will that fix your issue?

Yes.



Also, the whole functionality of Watchlistarr can be utilized using Radarr Settings→Lists→+→Plex Watchlist (or Plex Watchlist RSS)
![image](https://github.com/nylonee/watchlistarr/assets/8375129/4be34994-05a4-4915-89a5-c45db1ffd0fe)

**Comment by nylonee** [comment]
Thanks, I'll get coding away at a solution for the ignored items :)

Yes correct, Sonarr and Radarr have built-in functionality for the RSS feeds, however they're set to 6 hour intervals. They do not plan to add a way to customize the intervals, as indicated by [this comment](https://github.com/Sonarr/Sonarr/issues/4123#issuecomment-734433671). In addition, calling the ImportListSync Sonarr/Radarr API does not trigger Plex Watchlist RSS Syncs.

The watchlistarr solution is for those who want to have a similar functionality, but with customizable intervals, since Sonarr/Radarr will probably never implement this feature, and they make it difficult for users to trigger it otherwise.

**Comment by ALERTua** [comment]
Not very nice of them.
I would add this as an initial concept for your application in the first block of readme.
