### ISSUE TITLE
"Refreshed the access token expiry" is confusing.

### ISSUE THREAD

**Issue by glensc** [nylonee/watchlistarr#123]
First I thought the message was fetching refresh token for the plex token, and that got me thinking, where does it store the  refresh token, in memory? didn't see anything in the disk.

But looking at the source, it just sends a test request (aka ping) and does nothing with the result?:
- https://github.com/nylonee/watchlistarr/blob/9b31fadf9761efc52b91550372b39a2812bc6ae6/src/main/scala/plex/PlexUtils.scala#L36-L50

**Comment by nylonee** [comment]
Ah yeah, this confused me as well, it turns out that Plex handles 'token refresh' in a different way

It looks like when the token is validated on the Plex size, it's also "renewed" in their backend. If the token were a JWT, it would have a claims set that would have a fixed expiry date, but because it's not a JWT, I guess Plex just decides they can do whatever they want with their token.

Pinging the Plex token regularly ensures that it does not get invalidated on the Plex backend.

We only have empirical evidence to support this - I've been running the same token on my server for 6 months and it hasn't expired, so that's a big step up from the previous expiry times (1-2 months on Overseer)
