### ISSUE TITLE
Warning on High Response Time for Asynchronous Events

### ISSUE THREAD

**Issue by n1nj444** [nylonee/watchlistarr#147]
## Issue Description
I've encountered a warning in the logs regarding high response times for handling asynchronous events, which may indicate that the CPU is starving. 

## Log Details

`2024-05-03T08:45:35.906Z [WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.`

Could you please guide me on where in the codebase I should look to address this issue? Any advice on modifications or configurations that could help resolve this warning would be greatly appreciated.

Thank you!

**Comment by nylonee** [comment]
This is likely because you've got a lot of things to "watchlist" and it's taking longer than your interval you set to sync everything. Try adding a couple of seconds to your sync interval.

**Comment by n1nj444** [comment]
Is this the correct parameter?

`REFRESH_INTERVAL_SECONDS`

I have set it to 120 seconds. What should I change it to in order to stop getting this warning log?

**Comment by nylonee** [comment]
Ah hmm, if it's set to 120 seconds then that wouldn't be the issue. I've usually seen this problem when it's set to 5 seconds or 10 seconds.

What are you running Watchlistarr on? Is it a raspberry pi?

**Comment by n1nj444** [comment]
I'm on a DS918+ (Synology) in a container with Docker and my conf is : 

![image](https://github.com/nylonee/watchlistarr/assets/39305378/691870de-0599-4492-a2ad-4f46d02b509e)

**Comment by n1nj444** [comment]
Bump

**Comment by nylonee** [comment]
Sorry, been a slow few weeks for me. I'm able to replicate this issue by reducing the number of CPUs my app uses, and setting the refresh to 10-ish seconds. Basically, I think this warning indicates that you don't have enough compute power to handle watchlistarr plus all the other things you have on your Synology. This may be continuous, or just during very specific times (e.g. when somebody starts transcoding and your CPU spikes to 100%).

There's more (very technical) information [here](https://typelevel.org/cats-effect/docs/core/starvation-and-tuning#not-enough-cpus) 

It's not a huge issue for Watchlistarr, because it will just handle the sync as fast as it can. There's not much else I can do around this so I'll close this ticket :)

**Comment by lovegronvall** [comment]
I have the same problem, interval set to 1200 seconds on a Mac Mini.
